version: "3.9"

services:
  app:
    build: .
    container_name: scraping-news
    ports:
      - "${PORT}:8501"
    volumes:
      - ./data:/app/data
    environment:
      - STREAMLIT_SERVER_PORT=8501