name: docker-build

on:
  push:
    branches:
      - master # masterブランチにpushされたときに実行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Docker build
        run: |
          docker build -t scraping-news ./scraping-news