name: Run Tests

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: 3.11

      - name: Install dependencies
        working-directory: ./scraping-news
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - name: Run tests
        working-directory: ./scraping-news
        run: |
            PYTHONPATH=. pytest
